[build]
rustflags = ["-C", "relocation-model=static", "-C", "lto", "-C", "link-args=--image-base=0xffffffff80000000 -z separate-code"]

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
