[build]
target = "x86_64-unknown-uefi.json"
# target = "x86_64-unknown-linux-gnu.json"
# rustflags = ["-C", "relocation-model=static", "-C", "lto", "-C", "link-args=--image-base=0x00100000 --omagic"]
# rustflags = ["-C", "target-feature=-mmx,-sse,-soft-float"]

[target.x86_64-unknown-linux-gnu]
linker = "/opt/homebrew/opt/llvm/bin/ld.lld"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
