[workspace]
members = [
  "bball",
  "bench",
  "gbench",
  "ghello",
  "ghello2",
  "hello",
  "hello2",
  "life",
  "noiz2bg",
  "winhello",
  "test",
]

[profile.release]
lto = true
opt-level = "z"
