
[workspace]
members = [
  "bball",
  "gbench",
  "ghello",
  "hello",
  "hello2",
  "life",
  "noiz2bg",
]

[profile.release]
lto = true
opt-level = "z"

[workspace.dependencies]
megstd = {path = "../lib/megstd"}
